services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: automotive_catalog 
    ports:
      - "5432:5432"
    volumes:
      - ./infrastructure/postgres:/docker-entrypoint-initdb.d 
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d automotive_catalog"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  user-service:
    build:
      context: ./UserGatewayService
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: "Host=db;Database=automotive_auth;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
      JWT_KEY: ${JWT_KEY}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_AUDIENCE: ${JWT_AUDIENCE}
    depends_on:
      db:
        condition: service_healthy

  catalog-service:
    build:
      context: ./VehicleCatalogService
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: "Host=db;Database=automotive_catalog;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      CLOUDINARY_URL: ${CLOUDINARY_URL}
      # FIXED: Catalog now needs these to validate tokens for My Listings/Delete
      JWT_KEY: ${JWT_KEY}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_AUDIENCE: ${JWT_AUDIENCE}
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    env_file:
      - .env
    environment:
      - VITE_EMAILJS_SERVICE_ID=${VITE_EMAILJS_SERVICE_ID}
      - VITE_EMAILJS_TEMPLATE_ID=${VITE_EMAILJS_TEMPLATE_ID}
      - VITE_EMAILJS_PUBLIC_KEY=${VITE_EMAILJS_PUBLIC_KEY}
    depends_on:
      - user-service
      - catalog-service

  nginx:
    build:
      context: ./infrastructure/nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - user-service
      - catalog-service
    restart: always

volumes:
  pgdata:
